### ISSUE TITLE
Invalid controller [\PHPCI\Controller\PHPCIController]: PHPCI does not exist

### ISSUE THREAD

**Issue by ghost** [Block8/PHPCI#246]
---

Hi, I just got through the installation process and I have a few remarks : 
- You should add the **PDO extension** as prerequisite : the console installation warns us at the end of the installation process when the browser installation just stops without saying anything right after the smtp configuration.
- For Apache users, don't forget to configure SELinux to get the write rights
- I had the "session/login" not found issue for a while that I fixed by configuring the VHOST and public/.htaccess with 

``` apache
<VirtualHost phpci.local:80>
     DocumentRoot  /var/www/html/PHPCI/public
     ServerName    phpci.local

     <Directory /var/www/html/PHPCI/public>
          DirectoryIndex index.php
          Options Indexes FollowSymlinks MultiViews
          Require all granted
          AllowOverride All
     </Directory>
</VirtualHost>
```

``` apache
DirectoryIndex index.php

<IfModule mod_rewrite.c>
    RewriteEngine On  
    RewriteCond %{ENV:REDIRECT_STATUS} ^$
    RewriteRule ^index\.php(/(.*)|$) %{CONTEXT_PREFIX}/$2 [R=301,L]

    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule .? - [L]
    RewriteCond %{REQUEST_URI}::$1 ^(/.+)(.+)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]
    RewriteRule .? %{ENV:BASE}index.php [L]
</IfModule>

<IfModule !mod_rewrite.c>
    <IfModule mod_alias.c>
        RedirectMatch 302 ^/$ /index.php/
    </IfModule>
</IfModule>
```

---

I just got out of the session/login hell and went into that new error : 

```
array(4) { 
    ["message"]=> string(77) "Invalid controller [\PHPCI\Controller\PHPCIController]: PHPCI does not exist." 
    ["file"]=> string(64) "/var/www/html/PHPCI/vendor/block8/b8framework/b8/Application.php"
    ["line"]=> int(87) 
    ["trace"]=> string(275) 
    "#0 /var/www/html/PHPCI/vendor/block8/b8framework/b8/Application.php(66): b8\Application->initController() 
    #1 /var/www/html/PHPCI/PHPCI/Application.php(28): b8\Application->initRequest() 
    #2 /var/www/html/PHPCI/public/index.php(18): PHPCI\Application->handleRequest() 
    #3 {main}"
}

Notice: Undefined index: PATH_INFO in /var/www/html/PHPCI/PHPCI/Application.php on line 52

Notice: Undefined index: REDIRECT_PATH_INFO in /var/www/html/PHPCI/PHPCI/Application.php on line 53

array(8) { 
    ["PATH_INFO"]=> NULL 
    ["REDIRECT_PATH_INFO"]=> NULL 
    ["REQUEST_URI"]=> string(27) "/PHPCI/public/session/login" 
    ["PHP_SELF"]=> string(10) "/index.php" 
    ["SCRIPT_NAME"]=> string(10) "/index.php" 
    ["DOCUMENT_ROOT"]=> string(26) "/var/www/html/PHPCI/public" 
    ["SCRIPT_FILENAME"]=> string(36) "/var/www/html/PHPCI/public/index.php" 
    ["SERVER_SOFTWARE"]=> string(42) "Apache/2.4.6 (Fedora) PHP/5.5.7 SVN/1.7.14" 
}
```

_Can you tell me if there is something I missed ?_

**Comment by lakshmi28gsrl** [comment]
Iam trying in localhost add htaccess code , mode_rewrite is enable but iam having same problem url http://localhost/PHPCI/session/login redirecting to 404. Can you help us in solving this issue.
